# Generated by Django 3.1.4 on 2020-12-07 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aml_assess', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sanctioned',
            new_name='Sanction',
        ),
    ]
