# Generated by Django 3.1.4 on 2020-12-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_assess', '0004_potentialmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialmatch',
            name='match',
            field=models.BooleanField(default=True),
        ),
    ]
